apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.configmap.name }}
data:
  prometheus.yml: |
    
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets: ['prometheus-service:9090']
