apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.rule.name }}
data:
  prometheus.rules: |
    
    groups:
    - name: my-rules
      rules:
      - alert: NodeCPUHigh
        expr: node_cpu_seconds_total{mode="idle"} / node_cpu_seconds_total < 0.2
        for: 1m
        labels:
          severity: critical
      - alert: HighRequestLatency
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: page
        annotations:
          summary: "High request latency"
