apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: prometheus
spec:
  ports:
  - port: {{ .Values.prometheus.servicePort }}
    targetPort: {{ .Values.prometheus.servicePort }}
  selector:
    app: prometheus