apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image }}
        imagePullPolicy: {{ .Values.prometheus.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.prometheus.servicePort }}
        volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus
        - name: prometheus-config
          mountPath: /etc/prometheus/
        - name: prometheus-rules
          mountPath: /etc/prometheus/rules/
      initContainers:
        - name: prometheus-data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
          - name: prometheus-data
            mountPath: /data
      volumes:
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: my-prometheus-pvc
      - name: prometheus-config
        configMap:
          name: {{ .Values.prometheus.configmap.name }}
      - name: prometheus-rules
        configMap:
          name: {{ .Values.prometheus.rule.name }}