apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-aws-ebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0ac1c556b8c6a1ca9
    csi.storage.k8s.io/fstype: ext4